chat/urls.py
# chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

nudger/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include

import quizbot.urls
from users import views as user_views
import sms_nudger.urls
import convoscript.urls
import faqbot.urls

from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

# Suitable for development, not production
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include(sms_nudger.urls)),
    path("admin/", admin.site.urls),
    path('chat/', include('chat.urls')),
    path('chat-async/', include('chat_async.urls')),
    path("convoscript/", include(convoscript.urls)),
    path("", include("sms_nudger.urls")),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(
            template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("profile/", user_views.profile, name="profile"),
    path("register/", user_views.register, name="register"),

    path(
        "qary-7.ico",
        RedirectView.as_view(url=staticfiles_storage.url("qary-7.ico")),
    ),
    path("faq/", include(faqbot.urls)),
    path("quiz/", include(quizbot.urls)),
]

# if not settings.RENDER:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)

sms_nudger/urls.py
from django.urls import path
from .views import (
    # PostListView,
    # PostDetailView,
    # PostCreateView,
    # PostUpdateView,
    # PostDeleteView,
    NudgeListView,
    NudgeCreateView,
    NudgeDeleteView
)
from . import views

urlpatterns = [
    path('', views.home, name='sms-nudger-home'),
    path('about/', views.about, name='sms-nudger-about'),
    path('status/', views.status, name='sms-nudger-status'),
    path('nudges/', NudgeListView.as_view(), name='nudge-list'),
    path('nudge/new/', NudgeCreateView.as_view(), name='nudge-create'),
    path('nudge/<int:pk>/delete', NudgeDeleteView.as_view(), name='nudge-delete')
    # path('posts/', PostListView.as_view(), name='sms-nudger-post-home'),
    # path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    # path('post/new/', PostCreateView.as_view(), name='post-create'),
    # path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    # path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete')
]

sms_nudger/models.py
from django.db import models
from django.db.models.signals import post_save, pre_save, m2m_changed

from django.utils import timezone

from django.urls import reverse

from django.contrib.auth.models import User
from django.contrib.auth.hashers import make_password

from sms_nudger.tasks import email_nudge, sms_nudge, crontab_email_nudge, crontab_sms_nudge


class Class(models.Model):
    name = models.CharField(null=True, blank=True, max_length=128, help_text="Name of a class at the university")


class Student(models.Model):
    """ Contains data downloaded from Canvas to RDS and periodically updated by cron job """
    first_name = models.CharField(null=False, max_length=128,
                                  help_text="Used in addressing the student in messages."
                                  )
    last_name = models.CharField(null=False, max_length=128, help_text="Used to identify student in forms")
    email = models.EmailField(null=False, max_length=128, default='', help_text="Used to send nudges to students when selected as the delivery method")
    mobile_number = models.CharField(max_length=32, help_text="Used to send nudges to students when selected as the delivery method")
    txt_ok_ind = models.BooleanField(null=False, default=True, help_text="Indicates the student accepted receiving texted nudges")
    email_ok_ind = models.BooleanField(null=False, default=True, help_text="Indicates the student accepted receiving email nudges")
    dim_pgm_of_study_cur = models.CharField(null=False, max_length=128, default='', help_text="?????????")
    birth_date = models.DateField(default='', help_text="Birthday in YYYY-MM-DD")
    overall_credits = models.FloatField(null=False, default=0.0, help_text="Shows the student's total number of course credits earned so far")
    overall_gpa = models.FloatField(null=False, default=0.0, help_text="Shows the student's cumulative GPA")
    canvas_user_id = models.ForeignKey(User, null=False, on_delete=models.CASCADE, default='', help_text="The student's id in the Canvas LMS")

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

# Nudge columns: scheduled_datetime, sent_datetime, student (ForeignKey(Student)), nudge_message, nudge_subject, nudge_sender, nudge_type (CharField(max_len=64, choices=['immediate_email', 'scheduled_email', 'immediate_sms', 'scheduled_sms']))'
# nudge_message, nudge_subject, nudge_sender, nudge_type (CharField(max_len=64, choices=['immediate_email', 'scheduled_email', 'immediate_sms', 'scheduled_sms']))'


class Message(models.Model):
    subject = models.CharField(null=False, max_length=128, default='', help_text="The subject of the nudge (128 characters or less)")
    body = models.TextField(null=False, default='', help_text="The message to send to students.")

    def __str__(self):
        return f'{self.subject}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Nudge(models.Model):
    scheduled_datetime = models.DateTimeField(default='', help_text="The date/time selected to send the nudge. If left empty, the nudge will send immediately after saving.")
    sent_datetime = models.DateTimeField(blank=True, null=True, help_text="When the nudge was sent")
    # student = models.ForeignKey(Student, null=False, on_delete=models.CASCADE, default='', help_text="The recipient of a nudge")
    student = models.ManyToManyField(Student, help_text="The students who will receive the message")
    nudge_sender = models.CharField(null=False, max_length=128, default='', help_text="The instructor who scheduled the nudge (128 characters or less).")
    choices = [('immediate_email', 'Immediate Email'),
               ('scheduled_email', 'Scheduled Email'),
               ('immediate_sms', 'Immediate SMS'),
               ('scheduled_sms', 'Scheduled SMS')]
    nudge_type = models.CharField(max_length=64, choices=choices, default='immediate_email', help_text="Immediate emails/SMS will be sent upon submiting this form.  Scheduled emails or SMSs will be sent out at a time you schedule.")
    message = models.ForeignKey(Message, null=False, default=0, on_delete=models.RESTRICT, help_text="Each message contains a subject and body.  Only the subject is currently displayed.")

    def __str__(self):
        return f'{self.message} - {self.scheduled_datetime}'

    # Collected the nudge data
    def save(self, *args, **kwargs):
        # Saves the message as a Nudge Record

        super().save(*args, **kwargs)

# Sends the Nudge instance data to the right function for scheduling
# This should not be part of the Nudge class
def nudge_scheduler(sender, instance, action, **kwargs):

    if action == 'post_add':
        for student in instance.student.all():
            if student.email_ok_ind == True and (instance.nudge_type == 'immediate_email' or instance.nudge_type == 'scheduled_email'):
                print(f"EMAIL TRUE: {student.first_name}")

            # Selects the function based on delivery method and time
            # Self values are for message content
            # Regular values are for student information
            # These functions also save to Celery models ("Task results" and, possibly "Periodic tasks")
                if(instance.nudge_type == 'immediate_email'):
                    email_nudge(
                        student.first_name,
                        student.email,
                        instance.message.body
                    )
                elif(instance.nudge_type == 'scheduled_email'):
                    crontab_email_nudge(
                        student.first_name,
                        student.email,
                        instance.message.body,
                        instance.scheduled_datetime
                    )
                else:
                    return "Error"

            if student.email_ok_ind == True and (instance.nudge_type == 'immediate_sms' or instance.nudge_type == 'scheduled_sms'):
                print(f"SMS TRUE: {student.first_name}")

                if(instance.nudge_type == 'immediate_sms'):
                    sms_nudge(
                        student.first_name,
                        student.phone,
                        instance.message.body
                    )
                elif(instance.nudge_type == 'scheduled_sms'):
                    crontab_sms_nudge(
                        student.first_name,
                        student.phone,
                        instance.message.body,
                        instance.scheduled_datetime
                    )
                else:
                    return "Error"

    else:
        print("NOOOOOOOOO!")


# Triggers nudge_scheduler when student field has been written to nudge
# ManyToManyFields have two steps - save and then add M2M field to instance
m2m_changed.connect(nudge_scheduler, sender=Nudge.student.through)


class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    # If a user is deleted, all their posts are deleted as well
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

sms_nudger/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator


class GenerateRandomUserForm(forms.Form):
    total = forms.IntegerField(
        validators=[MinValueValidator(50), MaxValueValidator(500)]
    )

sms_nudger/templates/sms_nudger/about.html
{% extends "sms_nudger/base.html" %}


{% block content %}

    <h1> About Nudger! </h1>

{% endblock content %}

sms_nudger/templates/sms_nudger/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if title %}
      <title> Prosocial Open Source Chatbot Framework | {{ title }} </title>
    {% else %}
      <title> Prosocial Open Source Chatbot Framework | qary </title>
    {% endif %}

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->

    <link rel="icon" href="{% static 'sms_nudger/qary-favicons/qary-7.ico' %}">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    {% block qary %}{% endblock %}

    <link rel="stylesheet" type="text/css" href="{% static 'sms_nudger/main.css' %}">

</head>
<body>
  <header class="site-header">
    <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="#">
          <img
          src="{% static 'sms_nudger/qary-logo/qary-logo-small.png' %}"
          height="20"
          alt="qary"
          loading="lazy"
          />
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarToggle">
          <div class="navbar-nav mr-auto">
            <a class="nav-item nav-link" href="{% url 'sms-nudger-home' %}">Home</a>
            <a class="nav-item nav-link" href="{% url 'sms-nudger-about' %}">About</a>
          </div>
          <!-- Navbar Right Side -->
          <div class="navbar-nav">
            {% if user.is_authenticated %}
              <a class="nav-item nav-link" href="{% url 'nudge-create' %}">New Nudge</a>
              <a class="nav-item nav-link" href="{% url 'nudge-list' %}">Nudges</a>
              <a class="nav-item nav-link" href="{% url 'faq-create' %}">New FAQ</a>
              <a class="nav-item nav-link" href="{% url 'faq-list' %}">FAQs</a>
              <a class="nav-item nav-link" href="{% url 'faq-upload' %}">Document Upload</a>
              <a class="nav-item nav-link" href="{% url 'faq-document-list' %}">Document List</a>
              <a class="nav-item nav-link" href="{% url 'quiz' %}">Quiz</a>
              <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
              <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
            {% else %}
              <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
            {% endif %}
          </div>
        </div>
      </div>
    </nav>
  </header>



  <main role="main" class="container">
    <div class="row">
      <div class="col-md-12">
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}{% endblock %}

<!--
      </div>
      <div class="col-md-4">
        <div class="content-section">
          <h3>Our Sidebar</h3>
          <p class='text-muted'>You can put any information here you'd like.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">Latest Posts</li>
              <li class="list-group-item list-group-item-light">Announcements</li>
              <li class="list-group-item list-group-item-light">Calendars</li>
              <li class="list-group-item list-group-item-light">etc</li>
            </ul>
          </p>
        </div>
      </div>
-->
    </div>
  </main>

  {% block javascript %}{% endblock %}


  <!-- Bootstrap Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</body>
</html>

sms_nudger/templates/sms_nudger/generate.html
<!DOCTYPE html>
<!-- dir=ltr means language direction is left-to-right rather than  rtl -->
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title>Generate Random Users with Celery</title>
    </head>
    <body>
        <h1><u> FORMS HANDELING IN DJANGO </u></h1
        <div style = "max-width:470px;">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btnbtn-primary" value="submit">
        </div>
    </body>
</html>

sms_nudger/templates/sms_nudger/home.html
{% extends "sms_nudger/base.html" %}
{% load static %}


{% block qary %}
<link rel='stylesheet' type="text/css" href="{% static 'sms_nudger/faceofqary-bundle/quizbot.css' %}">
<script defer src="{% static 'sms_nudger/faceofqary-bundle/quizbot.js' %}"></script>
{% endblock qary %}

{% block content %}

<h1> Qary's proactive side </h1>

<p> Nudging humans to be more prosocial and productive </p>

<h1> {{ section.title }} </h1>

{% for nudge in nudge_list %}
<h2>
    <a href="{{ nudge.get_absolute_url }}">
        {{ nudge.name }}
    </a>
</h2>
<p>{{ nudge.description|truncatewords:"60" }}</p>
{% endfor %}
{% endblock content %}

sms_nudger/templates/sms_nudger/nudge_confirm_delete.html
{% extends "sms_nudger/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Nudge</legend>
                <h2>Are you sure you want to delete the nudge "{{ object.message.subject }}" you scheduled to send {{object.student}} on {{object.scheduled_datetime}}?
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'nudge-list' %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

sms_nudger/templates/sms_nudger/nudge_form.html
{% extends "sms_nudger/base.html" %}
{% load crispy_forms_tags %}

{% block extrastyle %}
    {{ form.media }}
    <style>
    .selector h2 {
        margin: 0;
        padding: 8px;
        font-weight: 400;
        font-size: 15px;
        text-align: left;
        background: #005236;
        color: white;
    }
    </style>
{% endblock extrastyle %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nudge Creation</legend>
                {% crispy form %}
            </fieldset>
            <!-- <div class="form-group">
                <button class="btn btn-outline-info" type="Submit">Send</button>
            </div>
            -->
        </form>
    </div>
{% endblock content %}


{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            hideShow()
        })

        // call hideShow when the user clicks on the project_type dropdownlist
        $('#id_nudge_type').click(function(){
            hideShow()
        });
        function hideShow(){
            if(document.getElementById('id_nudge_type').value == "scheduled_email" || document.getElementById('id_nudge_type').value == "scheduled_sms")
                {
                    $('#div_id_scheduled_datetime').show();
                }
            else
                {
                    $('#div_id_scheduled_datetime').hide();
                }
            }
    </script>
{% endblock %}



<div class="related-widget-wrapper">

sms_nudger/templates/sms_nudger/nudge_list.html
{% extends "sms_nudger/base.html" %}
{% load crispy_forms_tags %}

{% block extrastyle %}
    {{ form.media }}
    <style>
    .selector h2 {
        margin: 0;
        padding: 8px;
        font-weight: 400;
        font-size: 15px;
        text-align: left;
        background: #005236;
        color: white;
    }
    </style>
{% endblock extrastyle %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Nudge Creation</legend>
                {% crispy form %}
            </fieldset>
            <!-- <div class="form-group">
                <button class="btn btn-outline-info" type="Submit">Send</button>
            </div>
            -->
        </form>
    </div>
{% endblock content %}


{% block javascript %}
    <script type="text/javascript">
        $(document).ready(function(){
            hideShow()
        })

        // call hideShow when the user clicks on the project_type dropdownlist
        $('#id_nudge_type').click(function(){
            hideShow()
        });
        function hideShow(){
            if(document.getElementById('id_nudge_type').value == "scheduled_email" || document.getElementById('id_nudge_type').value == "scheduled_sms")
                {
                    $('#div_id_scheduled_datetime').show();
                }
            else
                {
                    $('#div_id_scheduled_datetime').hide();
                }
            }
    </script>
{% endblock %}



<div class="related-widget-wrapper">

sms_nudger/templates/sms_nudger/post-base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'sms_nudger/main.css' %}">

    {% if title %}
        <title>Django Blog - {{title}}</title>
    {% else %}
        <title>Django Blog</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'sms-nudger-home' %}">Django Blog</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{% url 'sms-nudger-home' %}">Home</a>
              <a class="nav-item nav-link" href="{% url 'sms-nudger-about' %}">About</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if user.is_authenticated %}
                <!-- <a class="nav-item nav-link" href="{% url 'post-create' %}">New Post</a> -->
                <a class="nav-item nav-link" href="{% url 'profile' %}">Profile</a>
                <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'register' %}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>



    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
          {% if messages %} 
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
          {% block content %}{% endblock %}
          
        </div>
        <div class="col-md-4">
          <div class="content-section">
            <h3>Our Sidebar</h3>
            <p class='text-muted'>You can put any information here you'd like.
              <ul class="list-group">
                <li class="list-group-item list-group-item-light">Latest Posts</li>
                <li class="list-group-item list-group-item-light">Announcements</li>
                <li class="list-group-item list-group-item-light">Calendars</li>
                <li class="list-group-item list-group-item-light">etc</li>
              </ul>
            </p>
          </div>
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

sms_nudger/templates/sms_nudger/post-home.html
{% extends "sms_nudger/post-base.html" %}

{% block content %}
    {% for post in posts %}
        <article class="media content-section">
          <img class="rounded-circle article-img" src="{{ post.author.profile.image.url }}">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href="#">{{ post.author }}</a>
              <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h2>
            <p class="article-content">{{ post.content }}</p>
          </div>
        </article>
    {% endfor %}
{% endblock content %}

sms_nudger/templates/sms_nudger/post_confirm_delete.html
{% extends "sms_nudger/post-base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

sms_nudger/templates/sms_nudger/post_detail.html
{% extends "sms_nudger/post-base.html" %}

{% block content %}
  <article class="media content-section">
    <img class="rounded-circle article-img" src="{{ object.author.profile.image.url }}">
    <div class="media-body">
      <div class="article-metadata">
        <a class="mr-2" href="#">{{ object.author }}</a>
        <small class="text-muted">{{ object.date_posted|date:"F d, Y" }}</small>
        {% if object.author == user %}
          <div>
            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'post-update' object.id %}">Update<a/>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'post-delete' object.id %}">Delete</a>
          </div>
        {% endif %}
      </div>
      <h2 class="article-title">{{ object.title }}</h2>
      <p class="article-content">{{ object.content }}</p>
    </div>
  </article>
{% endblock content %}

sms_nudger/templates/sms_nudger/post_form.html
{% extends "sms_nudger/post-base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="Submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

sms_nudger/templates/sms_nudger/status.html
{% extends "sms_nudger/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

<!-- {% block title %}{{ section.title }}{% endblock %} -->

{% block content %}
<h1>{{ section.title }}</h1>

{% for nudge in nudge_list %}
<h2>
  <a href="{{ nudge.get_absolute_url }}">
    {{ nudge.name }}
  </a>
</h2>
<p>{{ nudge.description|truncatewords:"60" }}</p>
{% endfor %}
{% endblock content %}